### ISSUE TITLE
Max ARISC CLK and step-rates ?

### ISSUE THREAD

**Issue by EmbDevices** [orangecnc/h3_arisc_firmware#13]
Interested about using this ARISC firmware with Klipper (https://github.com/KevinOConnor/klipper). Wondered what is the maximum AR100 clock frequency and well as what max step rates you were able to achieve ?

**Comment by MX-Master** [comment]
The actual loader (uboot script) works well only with **Armbian** builds based on **mainline kernel** (4.x). This loader script run by uboot before kernel start. **Armbian** builds based on legacy kernels (3.4.x) uses default **ARISC** firmware from **Allwinner**. This default firmware uploads to the destination after kernel start. That's why this CNC firmware isn't working in your test.

If you want to use only **Armbian** with the legacy kernel (3.4.x) you must use another firmware loader. This loader must upload the firmware after kernel start. You can use this one - https://github.com/MX-Master/opi1_devmem_write/blob/master/src/main.c

And, yea. All code of the firmware now have a good optimization for the pulses generation. But you can do better. Remove anything you want, use assembly, etc.

**Comment by MX-Master** [comment]
By the way, max GPIO toggling frequency is about 2 MHz. It's limited by memory bus.

**Comment by EmbDevices** [comment]
Thanks. With [WiringOP](https://github.com/zhaolei/WiringOP) I was able to obtain about 1.7 MHz, but the result had some pulse width deviation. Still I have not tried to isolate and run the process alone on single core.
Tested opi1_devmem_write, h3_arisc_firmware - works. I am currently trying to convince those guys at [Klipper](https://github.com/KevinOConnor/klipper) project to support such solution too. They have some port for TI AM335x.
Not sure if you looked at the [Klipper](https://github.com/KevinOConnor/klipper) project, it does have some architectural issues "SET_PIN not usable for laser engraving" (https://github.com/KevinOConnor/klipper/issues/133).

**Comment by MX-Master** [comment]
I tested many times the GPIO toggling process on isolated core. Linux kernel always do some housekeeping on this isolated core. Every millisecond (in not patched kernel). This work can take up to 50 us of time. So we have at least 50 us of latency every millisecond. That's why you see some pulse width deviation.

**Comment by EmbDevices** [comment]
Have you tried to change the values and the pattern of this 50us/1mS cycle, inquired Linux multi-core kernel developers ?
Also, how about LinuxCNC, I read can also be used for 3D printing ? Any observations, comparison with other firmwares ?

**Comment by MX-Master** [comment]
I tried a few kernel patches and different options to reduce this housekeeping latency. Without any good results. We can change housekeeping interval, but we can't disable it at all. Linux isn't a full RT system.

**LinuxCNC/Machinekit** is free, powerful and universal **CNC** software. You can make any type of **CNC** system using **LinuxCNC**. Any **CNC** router, any **3D** printer, anything you want. You can make any custom UI. You can use it locally or remotely.

**Comment by EmbDevices** [comment]
OK. Thanks, you saved me quite of time to perform those tests by myself. The AR100 solution seems the way to go. I will try LinuxCNC.
